import { chromium } from 'playwright-core';
const url = process.argv[2] || 'http://localhost:5173/#/settings/storage';
const browser = await chromium.connectOverCDP('http://localhost:9230');
const ctx = browser.contexts()[0];
const page = ctx.pages()[0];
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}\n${e.stack}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
await page.goto(url, { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(1500);
console.log(errors.join('\n---\n').slice(0, 4000));
process.exit(0);
